[2017-03-05 15:56:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-05 15:56:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/app_dev.php/api/user"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/app_dev.php/api/user\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-05 16:01:50] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 16:01:50] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 16:01:50] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 16:01:50] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 16:01:50] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 16:01:50] php.CRITICAL: Fatal Error: Call to undefined function AppBundle\Service\dump() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined function AppBundle\\Service\\dump() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php:80)"} []
[2017-03-05 16:01:50] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "dump" from namespace "AppBundle\Service"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"dump\" from namespace \"AppBundle\\Service\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php:80)"} []
[2017-03-05 16:01:50] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 16:02:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app_dev/~vrasquie/casapi/user"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app_dev/~vrasquie/casapi/user\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-05 16:02:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app_dev/~vrasquie/cas/api/user"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app_dev/~vrasquie/cas/api/user\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-05 19:51:17] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 19:51:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:51:17] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:51:17] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:51:17] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:51:17] php.CRITICAL: Fatal Compile Error: Access level to AppBundle\Controller\ApiController::getUser() must be protected (as in class Symfony\Bundle\FrameworkBundle\Controller\Controller) or weaker {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Access level to AppBundle\\Controller\\ApiController::getUser() must be protected (as in class Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller) or weaker at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:10)"} []
[2017-03-05 19:51:17] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Access level to AppBundle\Controller\ApiController::getUser() must be protected (as in class Symfony\Bundle\FrameworkBundle\Controller\Controller) or weaker" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php line 10 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Access level to AppBundle\\Controller\\ApiController::getUser() must be protected (as in class Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller) or weaker at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:10)"} []
[2017-03-05 19:51:17] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:51:23] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/flush","method":"GET"} []
[2017-03-05 19:51:23] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:51:23] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:51:23] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:51:23] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:51:23] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "flush.service". Did you mean one of these: "ask.service", "ldap.service"?" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3504 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"flush.service\". Did you mean one of these: \"ask.service\", \"ldap.service\"? at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3504)"} []
[2017-03-05 19:51:23] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:51:26] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/flush","method":"GET"} []
[2017-03-05 19:51:26] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:51:26] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:51:26] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:51:26] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:51:26] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "flush.service". Did you mean one of these: "ask.service", "ldap.service"?" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3504 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"flush.service\". Did you mean one of these: \"ask.service\", \"ldap.service\"? at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3504)"} []
[2017-03-05 19:51:26] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:53:09] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/flush","method":"GET"} []
[2017-03-05 19:53:09] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:53:09] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:53:09] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:53:09] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:09] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "flush.service". Did you mean one of these: "ask.service", "ldap.service"?" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3504 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"flush.service\". Did you mean one of these: \"ask.service\", \"ldap.service\"? at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3504)"} []
[2017-03-05 19:53:09] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:53:49] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 19:53:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:53:49] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:53:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:53:49] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:49] php.CRITICAL: Fatal Error: Call to undefined method AppBundle\Controller\ApiController::sendSuccess() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined method AppBundle\\Controller\\ApiController::sendSuccess() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:85)"} []
[2017-03-05 19:53:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "sendSuccess" of class "AppBundle\Controller\ApiController"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php line 85 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"sendSuccess\" of class \"AppBundle\\Controller\\ApiController\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:85)"} []
[2017-03-05 19:53:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:56:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-09 12:26:45] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-10 16:03:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/%7Buid%7D" (from "http://localhost:3000/account")" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/%7Buid%7D\" (from \"http://localhost:3000/account\") at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-10 16:04:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/%7Buid%7D" (from "http://localhost:3000/account")" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/%7Buid%7D\" (from \"http://localhost:3000/account\") at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-10 16:12:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/%7Buid%7D" (from "http://localhost:3000/account")" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/%7Buid%7D\" (from \"http://localhost:3000/account\") at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-10 16:12:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-10 16:12:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:60)"} []
[2017-03-10 16:12:40] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"ss","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/ss","method":"GET"} []
[2017-03-10 16:12:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:12:40] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:12:40] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:12:40] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-10 16:12:40] request.CRITICAL: Uncaught PHP Exception ErrorException: "Catchable Fatal Error: Object of class AppBundle\Entity\User could not be converted to string" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php line 37 {"exception":"[object] (ErrorException(code: 0): Catchable Fatal Error: Object of class AppBundle\\Entity\\User could not be converted to string at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php:37)"} []
[2017-03-10 16:12:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-10 16:18:29] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671?callback=jsonp_1489159106962_26115","method":"GET"} []
[2017-03-10 16:18:29] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:18:29] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:18:29] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:18:29] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:18:29] request.CRITICAL: Uncaught PHP Exception ErrorException: "Catchable Fatal Error: Object of class AppBundle\Entity\User could not be converted to string" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php line 37 {"exception":"[object] (ErrorException(code: 0): Catchable Fatal Error: Object of class AppBundle\\Entity\\User could not be converted to string at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php:37)"} []
[2017-03-10 16:18:29] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-10 16:19:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/service/call/acf2feb0-05a4-11e7-93ae-92361f002671"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/service/call/acf2feb0-05a4-11e7-93ae-92361f002671\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:60)"} []
[2017-03-10 16:19:23] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-10 16:19:24] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:19:24] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:19:24] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:19:24] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:19:24] request.CRITICAL: Uncaught PHP Exception ErrorException: "Catchable Fatal Error: Object of class AppBundle\Entity\User could not be converted to string" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php line 37 {"exception":"[object] (ErrorException(code: 0): Catchable Fatal Error: Object of class AppBundle\\Entity\\User could not be converted to string at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Service/LdapService.php:37)"} []
[2017-03-10 16:19:24] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-11 00:14:33] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/flush","method":"POST"} []
[2017-03-11 00:14:33] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-11 00:14:33] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-11 00:14:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-11 00:14:34] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-11 00:14:34] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-11 00:14:34] php.CRITICAL: Fatal Error: Call to undefined function AppBundle\Security\dump() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined function AppBundle\\Security\\dump() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-11 00:14:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "dump" from namespace "AppBundle\Security"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php line 135 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"dump\" from namespace \"AppBundle\\Security\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:16:41] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671?callback=jsonp_1489396600537_14461","method":"GET"} []
[2017-03-13 10:16:41] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-13 10:16:41] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:16:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-13 10:16:41] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-13 10:16:41] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-13 10:16:41] php.CRITICAL: Fatal Error: Call to undefined function AppBundle\Security\dump() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined function AppBundle\\Security\\dump() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:16:41] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "dump" from namespace "AppBundle\Security"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php line 135 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"dump\" from namespace \"AppBundle\\Security\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:16:56] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671?callback=jsonp_1489396600537_14461","method":"GET"} []
[2017-03-13 10:16:56] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-13 10:16:56] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:16:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-13 10:16:56] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-13 10:16:56] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-13 10:16:56] php.CRITICAL: Fatal Error: Call to undefined function AppBundle\Security\dump() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined function AppBundle\\Security\\dump() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:16:56] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "dump" from namespace "AppBundle\Security"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php line 135 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"dump\" from namespace \"AppBundle\\Security\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:17:07] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-13 10:17:07] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-13 10:17:07] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:17:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-13 10:17:07] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-13 10:17:07] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-13 10:17:07] php.CRITICAL: Fatal Error: Call to undefined function AppBundle\Security\dump() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined function AppBundle\\Security\\dump() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:17:07] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "dump" from namespace "AppBundle\Security"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php line 135 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"dump\" from namespace \"AppBundle\\Security\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Security/CasEnablerAuthenticator.php:135)"} []
[2017-03-13 10:21:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/flush"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/flush\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:60)"} []
[2017-03-15 10:59:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/auth" (from "http://localhost:3000/account")" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/auth\" (from \"http://localhost:3000/account\") at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:60)"} []
[2017-03-15 11:04:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/" (from "http://localhost:3000/account")" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/\" (from \"http://localhost:3000/account\") at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:05:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/service/call/"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/service/call/\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:13:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/cas.php"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/cas.php\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:14:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/cas.php"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/cas.php\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:15:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/cas.php"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/cas.php\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:27:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/fauth"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/fauth\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:49:42] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671?callback=jsonp_1489574981875_31684","method":"GET"} []
[2017-03-15 11:49:42] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:49:42] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:49:42] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:49:42] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:49:42] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\Entity\Service has no field or association named user" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\\Entity\\Service has no field or association named user at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.user = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:49:42] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:50:00] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671?callback=jsonp_1489575000619_23256","method":"GET"} []
[2017-03-15 11:50:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:50:00] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:50:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:50:00] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:50:00] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\Entity\Service has no field or association named user" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\\Entity\\Service has no field or association named user at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.user = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:50:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:50:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/cas.php"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/cas.php\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:65)"} []
[2017-03-15 11:50:50] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:50:50] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:50:50] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:50:50] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:50:50] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:50:51] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\Entity\Service has no field or association named user" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\\Entity\\Service has no field or association named user at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.user = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:50:51] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:51:11] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:51:11] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:51:11] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:51:11] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:51:11] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:51:11] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\Entity\Service has no field or association named user" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'user = :user': Error: Class AppBundle\\Entity\\Service has no field or association named user at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.user = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:51:11] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:52:28] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:52:28] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:52:28] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:52:28] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:52:28] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:52:28] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.users = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:52:28] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:52:40] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:52:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:52:40] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:52:40] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:52:40] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:52:40] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.users = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:52:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:53:36] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:53:36] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:53:36] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:53:36] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:53:36] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:53:37] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.users = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:53:37] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:53:44] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:53:44] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:53:44] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:53:44] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:53:44] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:53:44] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.users = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:53:44] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:53:46] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:53:46] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:53:46] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:53:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:53:46] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:53:46] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.users = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:53:46] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:54:21] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-15 11:54:21] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 11:54:21] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 11:54:21] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:54:21] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:54:21] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 49 near 'users = :user': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s FROM AppBundle\\Entity\\Service s WHERE s.users = :user AND s.id = :service at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-15 11:54:21] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 15:24:24] request.INFO: Matched route "app_main_allow". {"route":"app_main_allow","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::allowAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"app_main_allow"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/service/acf2feb0-05a4-11e7-93ae-92361f002671","method":"POST"} []
[2017-03-15 15:24:24] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-15 15:24:24] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-15 15:24:24] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 15:24:24] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 15:24:24] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO users_services (service_id, user_id) VALUES (?, ?)' with params [1, 8]:  SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « users_services_pkey » DETAIL:  La clé « (service_id, user_id)=(1, 8) » existe déjà." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 63 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO users_services (service_id, user_id) VALUES (?, ?)' with params [1, 8]:\n\nSQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « users_services_pkey »\nDETAIL:  La clé « (service_id, user_id)=(1, 8) » existe déjà. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:63, Doctrine\\DBAL\\Driver\\PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « users_services_pkey »\nDETAIL:  La clé « (service_id, user_id)=(1, 8) » existe déjà. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « users_services_pkey »\nDETAIL:  La clé « (service_id, user_id)=(1, 8) » existe déjà. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-03-15 15:24:25] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 20:54:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /~vrasquie/cas/cas.php"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php line 3920 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /~vrasquie/cas/cas.php\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/classes.php:3920, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/prod/appProdProjectContainerUrlMatcher.php:70)"} []
